
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: kir
  password: 123456

development:
  <<: *default
  database: test1


test:
  <<: *default
  database: test1


production:
  <<: *default
  database: test1
  username: kir
  password: 123456
